### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by ZafkielAleph** [AllTheMods/Spellbound#128]
### What would you like to know?

I am struggling to figure out how to get ice and fire working on my realistic world on spellbound of course oh biomes you'll go is active, which i believe all other spawns are working fine but rn no enemies from ice and fire are spawning i have seen no structures either besides the occasional village structure that has ice and fire stuff, what im asking is a solution to make it so ice and fire stuff spawns in biomes you'll go biomes either that be show me what is correct to do for getting it working or what, I do have the configs open and all its just i dont understand what goes where to make stuff work so it wont break.
![image_2022-05-09_080701362](https://user-images.githubusercontent.com/105196287/167357879-0ffff2e2-3735-44e2-b202-89fca7841516.png)
![image_2022-05-09_080753256](https://user-images.githubusercontent.com/105196287/167357988-eda36d81-bb7a-4dcb-938e-846a2fa26212.png)

**Comment by FieryForest** [comment]
discord me if this not help you @ FieryForest69#6162

Do not mess with the code, get it back to default code if you can and if you cant create a new world.
You can change where and how often ice and fire stuff spawns through the configs (see attached)

1) go to mods
![image](https://user-images.githubusercontent.com/105945277/169596545-2b68e8ef-24f2-436c-8eca-3d2fbb4ea5db.png)


2) search ice and fire and go to "config"
![image](https://user-images.githubusercontent.com/105945277/169596650-05a2b560-b111-475d-8673-de68c48186d5.png)


3) go to "modify" on "common"
![image](https://user-images.githubusercontent.com/105945277/169596703-36768fd8-6687-49ca-9a21-8d785537885b.png)


*things to watch out for *
- keep in mind that for generation rates, the lower the number the higher the chance for that thing to spawn per chunk. do not go below 4 otherwise your game will be extremely laggy 
- do not mess with the dragon skeleton spawn rate too much , they cause a LOT of lag
- do not press "Esc" and always press  the "back" button instead so you can see the "save" option.

**Comment by Mitchell5200** [comment]
Question answered?, Closing
