### ISSUE TITLE
[Bug]: Allthemodium and Vibranium ore not included in Djinni Ore Miner (Occultism Mod)

### ISSUE THREAD

**Issue by Tanyrus** [AllTheMods/Spellbound#26]
### Possible Fixes

Yes

### Modpack Version

2.1.5

### What happened?

The Ore Miner Djinni produces Unobtanium Ore (shown at a 0.0% chance), but doesn't show or produce Allthemodium ore or Vibranium Ore. I have also had it running with an Eternal Stella for days with no output of these two ores. 

### latest.log

https://gist.github.com/Tanyrus/5d774c7a26b581680481d1b170296338

**Comment by MadWomen** [comment]
i'll have to look at the loot tables for them, this isn't going to be a quick fix so its best to either use bees or mystical agriculture for now.

**Comment by Tanyrus** [comment]
I wasn't that worried since I had plenty but had just wanted to bring it up. Thanks for taking a look!

**Comment by MadWomen** [comment]
issue has been found and its going to be fixed next update.

**Comment by akmpe** [comment]
I would like to point out that this issue is still not fixed. the KubeJS file vibranium_ore.json has a spelling mistake in it, adding an extra "i" to vibranium. Where it says "vibrainium", it should say "vibranium". I have fixed it in my instance and can confirm that the Occultism ore miners can now produce vibranium ore.

**Comment by MadWomen** [comment]
somehow the previous fix didn't make it in somehow, it certainly will now!

**Comment by Mitchell5200** [comment]
Confirmed fixed in V2.2.7, Closing
