### ISSUE TITLE
[Question]: AllTheModium alloys

### ISSUE THREAD

**Issue by Mazila9968** [AllTheMods/Spellbound#86]
### AllTheModium alloys

We play with friends on this assembly and started to approach with AllTheModium alloys. There you need to scrape the stoves from IceAndFire. It is not clear where and how to look for representatives from the dragon family, and necessarily three different types, in order to build the above-mentioned structure. Flying in spectator mode, it was difficult to find large dragon lairs in the Other dimension. We did not understand where or how to look for dragons? Or are there some problems with the balance of their spawn?

**Comment by gxam** [comment]
fire spawn in basalt deltas, ice in mountains and lightning in desert.  only the female ones drop eggs and only T4 and T5.  (maybe T3, I forget.)

i spent hours doing worldgen looking for and killing the things.  they have stupid amounts of hp and do stupid amounts of damage.  i found a full set of vibranium gear in one of their lairs and i cheated in an allthemodium sword with 1k damage so i would only have to hit them 15 times instead of 150 and it was still an obnoxious grind.  this plus the bugged ATM star recipes has made me quit.

**Comment by ZephyrWindSpirit** [comment]
It's recommended to use a spectral eye amulet, as it lets you view mobs through walls. Dragon lairs spawn very LOW in the Other dimension, so you may want to start searching for large lairs lower then normal. 
It is a possibility on wrangling wild dragons into aiming their rage into the forge, but it would take a lot of chains and walls and being careful. Even tamed dragons using the forge kill you if you walk in their path. Personal experience.
The star is makeable in 2.2.7, but takes a lot of work. Enchanted ATM gear is easier to fight dragons, or DISTANCE.
