### ISSUE TITLE
[Question]: FeyWild mod

### ISSUE THREAD

**Issue by Mazila9968** [AllTheMods/Spellbound#87]
### What would you like to know?

What about the Feywild mod? Why is the mod added to the assembly, integrated into botania, but there are no blacksmith gnomes in the forges randomly generated and ore from this mod does not appear underground? How to use this mod as an alternative to Botany if all development paths are closed?

**Comment by ZephyrWindSpirit** [comment]
You need to make the rune of H-something, helvandir, I think, in order to summon a dwarf in the blacksmith houses of the overworld from that ancient runestone. Otherwise, Feywild is gated behind going through the alfheim portal, with the mead of kvasir. Its a later on alternative, if I'm understanding the question correctly. Once you are there, you can get the ores and such.
